# Generated by Django 3.2.13 on 2022-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('Timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
