# Generated by Django 3.2.13 on 2022-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=130),
        ),
    ]
